name: Package Extension

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Package VS Code extension
        run: npx -p @vscode/vsce vsce package --out dynamics-crm-webresources.vsix

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dynamics-crm-webresources.vsix
